### ISSUE TITLE
OnLoaded and Error state

### ISSUE THREAD

**Issue by AyoParadis** [botstar/chative-react-native-widget#7]
It seems like there is a delay when onLoaded becomes true and when the chat widget actually renders. 

My skeleton disappears when onLoaded is true. Can onLoaded be adjusted to only become true when the widget literally renders on screen. Right now it doesn't make for a good user experience. 

Also I can't see a way to handle if something goes wrong, for example if the channel id is no longer valid, the widget would simply load a blank screen instead of an error state. 

https://github.com/user-attachments/assets/5a60d298-19a4-49d5-8b50-827e046913b5

**Comment by dewly-tra** [comment]
Thank you, @AyoCodess . We will check the issue and update you on its status as soon as possible.

**Comment by chative-tu** [comment]
Hey @AyoCodess, I've already pushed the new version 0.5.2 with the corrected onLoaded event and a new callback for onError. You can give it a try

**Comment by AyoParadis** [comment]
> Hey @AyoCodess, I've already pushed the new version 0.5.2 with the corrected onLoaded event and a new callback for onError. You can give it a try

Thanks
